name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: macos-14    # Apple silicon runner
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - uses: abatilo/actions-poetry@v3
      with: { virtualenvs-create: true }
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
    - run: poetry install --all-extras --no-interaction
    - run: poetry run pre-commit run --all-files
    - run: poetry run pytest -q
